### ISSUE TITLE
PyPI checklist

### ISSUE THREAD

**Issue by dwf** [dwf/picklable_itertools#33]
- [x] Reorganize files to clean up namespace
- [x] Docstrings 
- [x] Naive implementations of combinations and permutations (based on filtering product, permutations, etc. -- see itertools docs)
- [x] At least one serialization test per public function
